import type { CanonicalField } from "../domain";
import type { MappingSynonymDictionary } from "./domain";

export const CANONICAL_FIELD_LABELS: Record<CanonicalField, string> = {
  firstName: "first name",
  lastName: "last name",
  email: "email",
  emailProfessional: "professional email",
  emailSecondary: "secondary email",
  emailPersonal: "personal email",
  company: "company",
  jobTitle: "job title",
  phone: "phone",
  phoneMobile: "mobile phone",
  phoneDirect: "direct phone",
  phoneStandard: "switchboard phone",
  country: "country",
  stateProvince: "state / province",
  city: "city",
  postalCode: "postal code",
  address: "address",
  salutation: "salutation",
  jobLevel: "job level",
  department: "department",
  localCompanyName: "local company name",
  website: "website",
  industry: "industry",
  leadSource: "lead source",
  campaignId: "campaign id",
  campaignName: "campaign name",
  campaignMemberStatus: "campaign member status",
  utmSource: "utm source",
  utmMedium: "utm medium",
  utmCampaign: "utm campaign",
  utmContent: "utm content",
  initialResponseDate: "initial response date",
  marketingConsent: "contact opt-in",
  salesFollowUpRequested: "sales follow-up requested",
  contactNotes: "contact notes",
};

export const DEFAULT_MAPPING_SYNONYMS: MappingSynonymDictionary = {
  firstName: [
    // English
    "firstname",
    "given name",
    "givenname",
    "forename",
    "contact first name",
    "registrant first name",
    "attendee first name",
    // French
    "prenom",
    "prénom",
    // Spanish
    "nombre",
    "nombre de pila",
    "primer nombre",
    // Portuguese
    "nome",
    "primeiro nome",
    "nome próprio",
    "nome proprio",
  ],
  lastName: [
    // English
    "lastname",
    "surname",
    "family name",
    "contact last name",
    "registrant last name",
    "attendee last name",
    // French
    "nom",
    "nom de famille",
    // Spanish
    "apellido",
    "apellidos",
    "primer apellido",
    "segundo apellido",
    // Portuguese (Portugal + Brazil)
    "apelido",
    "apelidos",
    "sobrenome",
    "último nome",
    "ultimo nome",
    "nome de família",
    "nome de familia",
  ],
  email: [
    // English
    "e mail",
    "email address",
    "contact email",
    "mail",
    // French
    "adresse email",
    "adresse mail",
    "courriel",
    // Spanish
    "correo electrónico",
    "correo electronico",
    "correo",
    "dirección de correo electrónico",
    "direccion de correo electronico",
    // Portuguese
    "correio eletrónico",
    "correio eletronico",
    "endereço de email",
    "endereco de email",
  ],
  emailProfessional: [
    "business email",
    "business email address",
    "work email",
    "work email address",
    "professional email address",
    "email professionnel",
    "adresse email professionnelle",
    "adresse mail professionnelle",
    "correo corporativo",
    "email corporativo",
    "correo de trabajo",
    "email profissional",
    "correio profissional",
  ],
  emailSecondary: [
    "alternate email",
    "alternative email",
    "backup email",
    "second email",
    "email secondaire",
    "adresse email secondaire",
    "courriel secondaire",
    "correo secundario",
    "correo alternativo",
    "email secundário",
    "email secundario",
    "correio alternativo",
  ],
  emailPersonal: [
    "private email",
    "personal email address",
    "email personnel",
    "adresse email personnelle",
    "correo personal",
    "email pessoal",
  ],
  company: [
    // English
    "company name",
    "organisation",
    "organization",
    "organisation name",
    "organization name",
    "account",
    "account name",
    "employer",
    "employer name",
    // French
    "societe",
    "société",
    "entreprise",
    // Spanish
    "empresa",
    "nombre de empresa",
    "nombre de la empresa",
    "compañía",
    "compania",
    "organización",
    "organizacion",
    "razón social",
    "razon social",
    // Portuguese
    "nome da empresa",
    "empresa",
    "companhia",
    "organização",
    "organizacao",
    "razão social",
    "razao social",
    "entidade empregadora",
  ],
  jobTitle: [
    // English
    "job role",
    "business title",
    "function",
    "role",
    "position",
    // French
    "fonction",
    "poste",
    // Spanish
    "cargo",
    "puesto",
    "puesto de trabajo",
    "función",
    "funcion",
    "rol",
    "título profesional",
    "titulo profesional",
    // Portuguese
    "cargo",
    "função",
    "funcao",
    "função profissional",
    "funcao profissional",
    "posição",
    "posicao",
  ],
  phone: [
    // English
    "phone number",
    "telephone",
    "telephone number",
    "work phone",
    // French
    "téléphone",
    "numéro de téléphone",
    "numero de telephone",
    "tel",
    // Spanish
    "teléfono",
    "telefono",
    "número de teléfono",
    "numero de telefono",
    // Portuguese
    "telefone",
    "número de telefone",
    "numero de telefone",
  ],
  phoneMobile: [
    "mobile",
    "cell phone",
    "cellphone",
    "mobile number",
    "portable",
    "téléphone mobile",
    "telephone mobile",
    "numéro de portable",
    "numero de portable",
    "móvil",
    "movil",
    "teléfono móvil",
    "telefono movil",
    "telemóvel",
    "telemovel",
    "telefone móvel",
    "telefone movel",
    "celular",
  ],
  phoneDirect: [
    "direct line",
    "direct dial",
    "direct number",
    "ligne directe",
    "téléphone direct",
    "telephone direct",
    "numéro direct",
    "numero direct",
    "teléfono directo",
    "telefono directo",
    "linha direta",
    "telefone direto",
  ],
  phoneStandard: [
    "standard",
    "switchboard",
    "switchboard number",
    "main phone",
    "main line",
    "standard téléphonique",
    "standard telephonique",
    "centralita",
    "central telefónica",
    "central telefonica",
    "telefone geral",
  ],
  country: [
    // English
    "country region",
    "country name",
    "nation",
    "billing country",
    // French
    "pays",
    // Spanish
    "país",
    "pais",
    "país región",
    "pais region",
    // Portuguese
    "país",
    "pais",
    "país região",
    "pais regiao",
  ],
  leadSource: [
    // English
    "source",
    "lead origin",
    "origin",
    "source detail",
    "leadsource",
    // Spanish
    "fuente",
    "fuente del lead",
    "fuente de lead",
    "origen del lead",
    "origen de lead",
    "origen",
    // Portuguese
    "fonte",
    "fonte do lead",
    "origem do lead",
    "origem",
  ],
  campaignMemberStatus: [
    // English
    "member status",
    "campaign status",
    "campaignmemberstatus",
    "attendance status",
    "attendee status",
    // French
    "statut de campagne",
    "statut du membre de campagne",
    "statut de participation",
    // Spanish
    "estado de campaña",
    "estado de campana",
    "estado del miembro de campaña",
    "estado del miembro de campana",
    "estado de asistencia",
    "estado de participación",
    "estado de participacion",
    // Portuguese
    "estado da campanha",
    "status da campanha",
    "estado do membro da campanha",
    "status do membro da campanha",
    "estado de presença",
    "estado de presenca",
    "estado de participação",
    "estado de participacao",
  ],
  stateProvince: ["state", "province", "region", "state province"],
  city: ["town", "locality"],
  postalCode: ["zip", "zip code", "postcode"],
  address: ["street address", "address line 1"],
  salutation: ["title", "honorific"],
  jobLevel: ["seniority", "seniority level"],
  department: ["business unit", "function department"],
  localCompanyName: ["local company", "company local name"],
  website: ["company website", "web site", "url"],
  industry: ["sector", "vertical"],
  campaignId: ["campaign identifier"],
  campaignName: ["campaign"],
  utmSource: [],
  utmMedium: [],
  utmCampaign: [],
  utmContent: [],
  initialResponseDate: ["first response date"],
  marketingConsent: ["marketing consent", "consent", "gdpr consent", "contact opt in"],
  salesFollowUpRequested: ["sales follow up", "sales follow-up"],
  contactNotes: ["notes", "contact note"],
};
