import type { CanonicalField } from "../domain";
import type { MappingSynonymDictionary } from "./domain";

export const CANONICAL_FIELD_LABELS: Record<CanonicalField, string> = {
  firstName: "first name",
  lastName: "last name",
  email: "email",
  company: "company",
  jobTitle: "job title",
  phone: "phone",
  country: "country",
  leadSource: "lead source",
  campaignMemberStatus: "campaign member status",
};

export const DEFAULT_MAPPING_SYNONYMS: MappingSynonymDictionary = {
  firstName: [
    "firstname",
    "given name",
    "givenname",
    "forename",
    "prenom",
    "prénom",
    "contact first name",
    "registrant first name",
    "attendee first name",
  ],
  lastName: [
    "lastname",
    "surname",
    "family name",
    "nom",
    "nom de famille",
    "contact last name",
    "registrant last name",
    "attendee last name",
  ],
  email: [
    "e mail",
    "email address",
    "business email",
    "business email address",
    "work email",
    "work email address",
    "contact email",
    "mail",
    "adresse email",
    "adresse mail",
    "courriel",
  ],
  company: [
    "company name",
    "organisation",
    "organization",
    "organisation name",
    "organization name",
    "account",
    "account name",
    "societe",
    "société",
    "entreprise",
    "employer",
    "employer name",
  ],
  jobTitle: [
    "job role",
    "business title",
    "function",
    "fonction",
    "role",
    "position",
    "poste",
  ],
  phone: [
    "phone number",
    "telephone",
    "telephone number",
    "téléphone",
    "numéro de téléphone",
    "numero de telephone",
    "tel",
    "mobile",
    "mobile phone",
    "work phone",
  ],
  country: [
    "country region",
    "country name",
    "pays",
    "nation",
    "billing country",
  ],
  leadSource: [
    "source",
    "lead origin",
    "origin",
    "source detail",
    "leadsource",
  ],
  campaignMemberStatus: [
    "member status",
    "campaign status",
    "campaignmemberstatus",
    "attendance status",
    "attendee status",
  ],
};
