name: Generate package lock

on:
  pull_request:
    paths:
      - package.json
      - .github/workflows/lockfile-artifact.yml

permissions:
  contents: read

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 22

      - name: Generate package-lock.json
        run: npm install --package-lock-only --ignore-scripts

      - name: Upload package lock
        uses: actions/upload-artifact@v4
        with:
          name: package-lock
          path: package-lock.json
